name: "Close stale PRs"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: "Thank you for your contribution. Unfortunately, this pull request is stale because it has been open 30 days with no activity. Please remove the stale label or comment or this will be closed in 7 days."
          days-before-pr-stale: 30
          days-before-pr-close: 7
          # do not close stale issues
          days-before-issue-stale: -1
          days-before-issue-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
